export const metadata = {
  title: "Orebi_NextJs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <>
        {children}
      </>

  );
}
